Objetivo 1
LuisArostegui/MyWallet pull request #6
Opened 2021-09-27 14:08 UTC by LuisArostegui

2021-09-27 17:38 UTC, JJ requested changes
Por favor, consulta los siguiente conceptos:
* Producto mínimamente viable.
* Qué es una historia de usuario
* Qué es la lógica de negocio.

y revisa un poco. También convendría que perfilaras unp oco más los tipos de usuarios.

2021-09-27 17:38 UTC, JJ commented on docs/historias_usuario.md
> +* Gestor, capacidad de añadir y modificar datos teniendo en cuenta las decisiones estrategicas.
Todos los conceptos (como decisiones estratégicas) tienen que estar bien definidos en las HUs

2021-09-27 17:38 UTC, JJ commented on docs/historias_usuario.md
> +* [HU4](https://github.com/LuisArostegui/RealFoodRecipeCreator/issues/5): Como gestor, quiero poder predecir el número de recetas que se van a ir añadiendo mes a mes, con dos semanas de antelación.
Una HU siempre tiene que mencionar el beneficio que obtiene el usuario de esa acción, y por supuesto el contexto de la misma. ¿Qué necesita el gestor para poder hacer eso? ¿Qué beneficio obtiene? ¿Para qué sirve predecir las recetas que se van a meter?

2021-09-27 17:38 UTC, JJ commented on docs/historias_usuario.md
> +* [HU1](https://github.com/LuisArostegui/RealFoodRecipeCreator/issues/2): Como consumidor, quiero poder ver recetas sin necesidad de introducir ingredientes.
¿Recetas de quién? ¿En qué contexto? ¿Qué beneficio obtiene? ¿Qué es "ver")
> Si se refiere a ver en la web, no es una HU para esta asignatura.

2021-09-27 17:38 UTC, JJ commented on docs/historias_usuario.md
> +* [HU3](https://github.com/LuisArostegui/RealFoodRecipeCreator/issues/4): Como publicador, quiero disponer de un informe de los ingredientes/recetas más vistas en la última semana.
Eso es una simple búsqueda.

2021-09-27 17:38 UTC, JJ commented on docs/historias_usuario.md
> +* [HU2](https://github.com/LuisArostegui/RealFoodRecipeCreator/issues/3): Como consumidor, quiero poder buscar recetas introduciendo parcialmente el nombre de esta.
También es una simple búsqueda.

2021-09-28 15:48 UTC, LuisArostegui commented on docs/historias_usuario.md
> +* Gestor, capacidad de añadir y modificar datos teniendo en cuenta las decisiones estrategicas.
Resuelto. Describo a consumidor. Gestor añado funciones que puede realizar.

2021-09-28 15:49 UTC, LuisArostegui commented on docs/historias_usuario.md
> +* [HU4](https://github.com/LuisArostegui/RealFoodRecipeCreator/issues/5): Como gestor, quiero poder predecir el número de recetas que se van a ir añadiendo mes a mes, con dos semanas de antelación.
Resuelto. Sigo la plantilla " Como <perfil de usuario>, <quiero> <para> " para realizar correctamente las historias de usuario.

2021-09-28 15:51 UTC, LuisArostegui commented on docs/historias_usuario.md
> +* [HU3](https://github.com/LuisArostegui/RealFoodRecipeCreator/issues/4): Como publicador, quiero disponer de un informe de los ingredientes/recetas más vistas en la última semana.
Resuelto. Cambio de historia de usuario.

2021-09-28 15:51 UTC, LuisArostegui commented on docs/historias_usuario.md
> +* [HU2](https://github.com/LuisArostegui/RealFoodRecipeCreator/issues/3): Como consumidor, quiero poder buscar recetas introduciendo parcialmente el nombre de esta.
Resuelto. Cambio de historia de usuario.

2021-10-01 15:19 UTC, JJ requested changes
El desarrollo debe empezar por el hito 0. No puedes poner todas las HUs en el hito 4. Y todos los hitos deben ser productos mínimamente viables.

2021-10-03 17:20 UTC, LuisArostegui commented
Resuelto. Modifico milestones e historia de usuario 1

2021-10-04 15:56 UTC, JJ requested changes
Una "estructura de datos" no es un PMV, lo sería si estuviera en forma de código y compilara. Que permita realizar búsquedas, ¿cómo va a permitirlo una estructura de datos? No tiene ninguna funcionalidad, es una estructura de datos.

2021-10-04 15:56 UTC, JJ commented on docs/historias_usuario.md
> +* Gestor, capacidad de añadir y modificar datos teniendo en cuenta las decisiones estrategicas y ultimas noticias acerca de la alimentación y salud.
Deberás clarificar, y bastante, qué son las "decisiones estratégicas" y cóm ovan a afectar al consumidor.

2021-10-04 15:56 UTC, JJ commented on docs/historias_usuario.md
> +* [HU1](https://github.com/LuisArostegui/RealFoodRecipeCreator/issues/2): Como consumidor, quiero poder introducir un ingrediente para realizar una búsqueda de las recetas que se pueden realizar con
No indica ningún beneficio, no indica qué contexto (por qué quiere recetas), y es sólo una búsqueda. No hay ninguna lógica de negocio.

2021-10-04 15:56 UTC, JJ commented on docs/historias_usuario.md
> +* [HU2](https://github.com/LuisArostegui/RealFoodRecipeCreator/issues/3): Como consumidor, quiero poder agrupar recetas en categorías para simplificar la búsqueda de recetas.
Sólo mencionas la búsqueda, "agrupar por categorías" no está claro qué significa, no hay ninguna lógica d enegocio.

2021-10-04 15:56 UTC, JJ commented on docs/historias_usuario.md
> +* [HU3](https://github.com/LuisArostegui/RealFoodRecipeCreator/issues/4): Como consumidor, quiero disponer de un informe de los ingredientes/recetas más vistas por los usuarios en la última semana pa
Sigue siendo sólo búsqueda. Esto no corresponde a la lógica de negocio que indicaste en el anterior objetivo, y dónde podrías haber metido algoritmos tipo problema de la mochila para hallar recetas óptimas. Por favor, revisa todo, clarifica la lógica de negocio, y reorganiza las historias de usuario en sus milestones.
La ingeniería de software debe resolver problemas. Si no tienes claro cuál es el problema, es difícil que lleves a cabo los pasos necesarios para resolverlo.

2021-10-05 19:10 UTC, LuisArostegui commented
@JJ he modificado descripción del proyecto. He modificado todo como para volver a completar el hito 0 y he añadido lo necesario para completar el hito 1.  

* He añadido, bajo mi punto de vista, una lógica de negocio al indicar como se transforman y calculan resultados desde los datos.

2021-10-06 10:39 UTC, JJ approved these changes
Las HUs y eso dejan algo que desear, pero los primeros milestones parecen adecuados para salir adelante (no así el resto). Aunque no ha acabado, te asigno a @venrra para el siguiente objetivo.

2021-10-06 10:39 UTC, JJ commented on README.md
> +La idea del proyecto viene de querer ayudar a aquellas personas que necesiten registrar sus gastos/ingresos para lograr una salud financiera para evitar tener problemas con el dinero. El principal pr
Sigues sin especificar la lógica de negocio. No hay nada de predecir, calcular...

2021-10-06 10:39 UTC, JJ commented on docs/historias_usuario.md
> +* **Estudiante**, estudia informática con 20 años, no tiene trabajo, solo estudia en la universidad de Granada. Su fuente de ingresos son sus padres que le dan una paga de 150€ al mes. Cada semana le
Typos: dia

2021-10-06 10:39 UTC, JJ commented on docs/historias_usuario.md
> +* **Jubilado**, tiene 65 años, no trabaja ni estudia nada. Vive tranquilo en su casa, solo paga facturas mes a mes. Quiere gastarse dinero en viajar por el mundo ya que no ha tenido la oportunidad du
typo: calculos
Tendrás que hacer algo más sustancioso que sumar cuantos gastos se han hecho en un mes. En los otros casos puedo más o menos preverlo, en este caso no veo el caso de uso. Seguro que un jubilado sabe sumar sus gastos. Siendo un caso simple, podría ir al hito 0, sin embargo.

2021-10-06 10:39 UTC, JJ commented on docs/historias_usuario.md
> +* [HU1](https://github.com/LuisArostegui/MyWallet/issues/2) Como trabajador, quiero saber cuanto dinero puedo ahorrar al año para realizar un análisis sobre mis gastos.
Una vez más, esto es sumar. Tampoco hay tanta lógica de negocio. Y si no es sumar sino que vas a predecir, tendrás que decir en base a que, el "dado que" es imprescindible en toda historia de usuario.

2021-10-07 12:45 UTC, merged